-- Database Query -----------

CREATE DATABASE COMPANY;
CREATE DATABASE IF NOT EXISTS COMPANY;		-- IF NOT EXISTS WILL GIVE WARNING IF DB ALREADY PRESENT
DROP DATABASE COMPANY;						-- THIS WILL DELETE THE DB
DROP DATABASE IF EXISTS COMPANY;			-- IF EXISTS ALSO GIVE WARNING IF DB WILL BE PRESENT ALREADY
SHOW DATABASES;								-- IT WILL SHOW ALL DATABASES NAME 
USE COMPANY;								-- 'USE' WILL USE THIS PARTICULAR DB
SELECT DATABASE();							-- IT WILL SHOW WHICH DB IS SELECTED CURRENTLY

-- Table Queries --------------------

-- CREATE TABLE table_name;
-- DROP TABLE table_name;
-- SHOW TABLES;
-- SELECT * FROM table_name;
-- INSERT INTO table_name(col1 , col2) VALUES (col1_value1,col2_value1), (col1_value2 , col2_value2),(col1_value3 , col2_value3),

CREATE TABLE EMP (			-- If you will execute directly this query then it will create table in college DB. to create in Company DB we have select that DB.
EMP_ID INT PRIMARY KEY,
NAME VARCHAR(50),
LOCATION VARCHAR(50)
);
-- NOW TO DELETE THE EMP TABLE FROM COLLEGE WE WILL DROP FROM THERE AFTER SELECTING COLLEGE DB.
USE COLLEGE;
SHOW TABLES;			-- THIS WILL SHOW ALL TABLE IN COLLEGE DB.
DROP TABLE EMP;


USE COMPANY;			-- SELECT COMPANY DB SO THAT EMP TABLE CAN CREATE UNDER THIS.
CREATE TABLE EMP (			-- If you will execute directly this query then it will create table in college DB. to create in Company DB we have select that DB.
EMP_ID INT PRIMARY KEY,
NAME VARCHAR(50),
LOCATION VARCHAR(50)
);

SELECT * FROM EMP;

INSERT INTO EMP (EMP_ID , NAME , LOCATION) 
VALUES (101 , 'AKSHAY' , 'MUMBAI'), (102, 'TANYA' , 'PUNJAB'), (103, 'AYUSH' , 'LUCKNOW');
SELECT * FROM EMP;

-- IF THERE IS ONLY ONE VALUE WE WANT TO INSERT AND WE KNOW TYPE OF DATA, ORDER ETC SO WE CAN INSERT LIKE BELOW ALSO.
INSERT INTO EMP VALUES(104, 'GURU' , 'GUJRAT');



-- ----------------------------------------- ASSIGNMENT ---------------------------------------------------------------
-- STEP - 1 --> CREATE A DB FOR A COMPANY CALLED XYZ AND CREATE A TABLE FOR EMPLOYEE HAVING FIELD EMP_ID, NAME AND SALARY
-- STEP - 2 --> INSERT THESE DATA INSIDE TABLE --> (101 , ADAM , 25000) , (102 , BOB , 30000) , (103 , CASEY , 40000)
-- STEP - 3 --> SELECT AND VIEW ALL YOUR DATA

CREATE DATABASE XYZ;
USE XYZ;
CREATE TABLE EMP_INFO (
EMP_ID INT PRIMARY KEY,
NAME VARCHAR(50),
SALARY INT(10));

INSERT INTO EMP_INFO (EMP_ID, NAME, SALARY) VALUES (101 , 'ADAM' , 25000) , (102 , 'BOB' , 30000) , (103 , 'CASEY' , 40000);
SELECT * FROM EMP_INFO;